#%RAML 1.0 Trait
usage: This reusable component is to apply client id enforcement policy to apis.
queryParameters:
  client_id:
    type: string
    required: true
  client_secret:
    type: string
    required: true