#%RAML 1.0 Trait
usage: This trait is used to track the mule records end to end.
headers:
      x-transaction-id:
        type: string
        required: false
        description: Transaction id to maintain over different request